### ISSUE TITLE
add linux to `vstgui/lib/cfont.cpp`

### ISSUE THREAD

**Issue by rghvdberg** [surge-synthesizer/vstgui#1]
```
@@ -42,6 +42,16 @@ namespace VSTGUI {
  static CFontDesc gNormalFontVerySmall ("Arial", 9); 
  static CFontDesc gSymbolFont ("Symbol", 13); 
 
#elif LINUX 
  static CFontDesc gSystemFont ("sans-serif", 12); 
  static CFontDesc gNormalFontVeryBig ("sans-serif", 18); 
  static CFontDesc gNormalFontBig ("sans-serif", 14); 
  static CFontDesc gNormalFont ("sans-serif", 12); 
  static CFontDesc gNormalFontSmall ("sans-serif", 11); 
  static CFontDesc gNormalFontSmaller ("sans-serif", 10); 
  static CFontDesc gNormalFontVerySmall ("sans-serif", 9); 
  static CFontDesc gSymbolFont ("sans-serif", 13); //FIXME what's the default Symbol font for LINUX ? 
 
#else 
  static CFontDesc gSystemFont ("Arial", 12); 
  static CFontDesc gNormalFontVeryBig ("Arial", 18); 
```

**Comment by baconpaul** [comment]
Thanks - I’ll try and find time to walk this through this weekend or early next week

**Comment by baconpaul** [comment]
Oh hey I just saw you don't have a default for symbol. Does symbol also crash ubuntu? If so can you ask @falktx or @jsakkine or other linux folks what a good default is? I would probably reject this diff with a FIXME and I think steinberg definitely would.

Can still patch it for us but was just peeking now and realized.

Thanks!

**Comment by rghvdberg** [comment]
I've tried it with 
`static CFontDesc gSymbolFont ("Symbol", 13)`
nothing happens, no crash
I don't think there's a default font for Symbol on Linux ¯\_(ツ)_/¯

**Comment by baconpaul** [comment]
Ok cool thanks
Will push through with symbol this week then

**Comment by baconpaul** [comment]
I moved this to https://github.com/surge-synthesizer/surge/issues/614 so I don't forget it in my next sweep of issues and am closing this one. Sorry to not get this in the morning's sweep fest.
