### ISSUE TITLE
Wrong "unsupported compiler" error

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/vstgui#5]
Here: https://github.com/surge-synthesizer/vstgui/blob/313faee9db026b1d6254c91d8650e7da58e005a5/vstgui/lib/vstguibase.h#L136

It checks an operating system, and then says that compiler isn't supported.

Additionally, please include ```defined(__FreeBSD__) || defined(__DragonFly__)``` along with ```defined(__linux__)``` because these OSes are very similar to Linux from the application standpoint.

**Comment by baconpaul** [comment]
Hi

Good catch. As I'm sure you saw, the cmake file is about 36 hours old and there's still plenty to do.

Where do you think we should add those "defined"s? That doesn't look like cmake syntax to me and __linux__ doesn't appear in our src or cmake. So some more clarity there would help. Thanks!

**Comment by baconpaul** [comment]
Oh - this is in our vstgui fork I see. Sorry - thought this was a comment on surge. This is all steinberg code plus a couple of minimal diffs to make surge work. Why do you want to change this (as opposed to make an adjustment in the surge parent?)

**Comment by baconpaul** [comment]
Fixed @ https://github.com/surge-synthesizer/vstgui/commit/3cea4e01aa4808715cd39cb76b12e6688aa32318
